### PR TITLE
Skip `find_package` for already present targets

### PR DESCRIPTION
**Pull request by GregTheMadMonk**
For #231.

Didn't properly test yet, and I don't know what to do with `msgpack-c` and `PkgConfig`, if anything needs to be done for them

### CODE REVIEW

**Comment by liuzicheng1987** [comment]
@GregTheMadMonk , thanks for the initiative. Let me know when this is finished (it appears that this is still a draft).

**Comment by xsun2001** [comment]
I would be appreciate if the same support is provided to toml format for better CMake/CPM intergration.

```cmake
if (REFLECTCPP_TOML)
    list(APPEND REFLECT_CPP_SOURCES
        src/reflectcpp_toml.cpp
    )
    if (TARGET tomlplusplus::tomlplusplus)
		target_link_libraries(reflectcpp PRIVATE tomlplusplus::tomlplusplus)
    else()
		if (MSVC)
	        target_link_libraries(reflectcpp PRIVATE "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/tomlplusplus${CMAKE_STATIC_LIBRARY_SUFFIX}")
	    else ()
	        target_link_libraries(reflectcpp PRIVATE "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libtomlplusplus${CMAKE_STATIC_LIBRARY_SUFFIX}")
	    endif ()
	endif()
endif()
```

**Comment by liuzicheng1987** [comment]
@GregTheMadMonk , what is status on this PR? It is still marked as a draft...is that on purpose? Do you want me to review and then potentially merge it?

**Comment by GregTheMadMonk** [comment]
@liuzicheng1987 yes, sorry, I was sidetracked by other tasks and kind of pushed this to the side.

Here I've rebased the branch to match your current `main`, added it for (I hope) all possible dependencies and tried to test the libraries and how they work with this patch. Aside from the following, everything worked fine as far as I can tell:
1. `CMakeLists.txt` in `yyjson` repo only provides a `yyjson` target, `yyjson::yyjson` needs to be provided manually as an alias after importing `yyjson` project. Similar situation with `bson_static`, `bson_shared` and `flatbuffers`. I've decided to leave it as is, as declaring an `ALIAS` library is not hard and this helps keep things uniform with what is expected from found packages
2. `msgpack` (I used `cpp_master` branch) throws a `no such file or directory` error on `#include <msgpack.h>` for some reason
3. `tinycbor` does not provide a `CMakeLists.txt` at all. I made it so that if a `tinycbor` target is present in the project (probably declared manually by a person who uses `tinycbor` with `cmake`), it is used instead of searching `vcpkg` paths. Didn't test it yet
4. Didn't test `benchmark` and `simdjson`

IDK if I should mark it as a regular PR or leave it a draft for now. It'd be great if someone else tested and verified that it doesn't break builds for them too.

**Comment by liuzicheng1987** [comment]
Hi @GregTheMadMonk , I am currently making some changes to the imports myself. I will resolve the conflicts and merge tomorrow.

**Comment by liuzicheng1987** [comment]
Hi @GregTheMadMonk, sorry it took me two weeks to review this, but I was making a lot of changes to the CMakeLists.txt as well. I have now resolved the merge conflicts and made sure that it compiles both with vcpkg and Conan. On my view, it's ready to be merged.

Are you OK with the changes I made?

**Comment by GregTheMadMonk** [comment]
@liuzicheng1987 thenk you! The changes are fine by me as long as they work, but I don't see why they wouldn't :)

The only question I have is, why did you switch `tomlplusplus::tomplplusplus` to just `tomlplusplus`?

**Pull request merged**
