### PR TITLE
Split reflect.cpp file into multiple source files

### PR DESCRIPTION
**Pull request by Altren**
Initially I wanted to go deeper with moving more stuff into cpp files where possible, but ClangBuildAnalyzer did not revealed any obvious parts, so I decided to commit only preparation changes.
Any suggestions what can be moved into cpp are welcome, and I'll create another PR

### CODE REVIEW

**Comment by liuzicheng1987** [comment]
Hi @Altren , why do you want to split the .cpp file into three smaller files? 

The reason I specifically didn't do this is that I want to make installation as simple as possible. Some people don't use CMake packages, but instead they want to simply include the code in their own build process. 

Being able to simply copy a single source file into your own source code makes this very easy.

**Comment by liuzicheng1987** [comment]
The changes to the CMake file seem fine, but I haven't taken a closer look yet...reducing duplicate code is always a good idea...

**Comment by Altren** [comment]
I splitted this into files, because I wanted to move more code into .cpp files and adding it into single file doesn't looks ok for me.
> Some people don't use CMake packages, but instead they want to simply include the code in their own build process.

Well, they already copy multiple headers anyway. I you want to keep it simple for such use cases I can add reflectcpp.cpp back and `#include` all new .cpp files into it.

**Comment by liuzicheng1987** [comment]
@Altren , at the moment reflectcpp.cpp is fairly short...I don't think there is much of a need to split it up further. It's just going to increase compile time and make things unnecessarily complicated.

However, if you can find significant portions of the code that you can put into source files, we could seriously think about splitting it up. I would be very happy if that were possible.

**Comment by Altren** [comment]
I updated my changes, so that both problem you mentioned are solved:
Compile time is the same as it was, since reflectcpp.cpp is a simple inclusion of other source files.
Only reflectcpp.cpp need to be added to the build, like it was before

**Comment by Altren** [comment]
But I'm ok if we keep this not merged until I'll do more useful changes, that require this split

**Pull request closed without merging**
