### PR TITLE
Add operator== to TaggedUnion.hpp

### PR DESCRIPTION
**Pull request by ttamttam**
Following @liuzicheng1987 advice (https://github.com/getml/reflect-cpp/issues/272#issuecomment-2492386937), I had a hard time converting my code in order to have it work in TaggedUnion.hpp.

Note sure at all that it is OK?

Best regards

### CODE REVIEW

**Comment by liuzicheng1987** [comment]
Looks good to me...the only thing I could think of is to maybe add a test. (Just put it with the JSON tests.)

**Comment by ttamttam** [comment]
I thank you. I'll add tests. But i won't be able to before the end of the year.

24 nov. 2024 20:13:53 Dr. Patrick Urbanke (劉自成) ***@***.***>:

**Comment by ttamttam** [comment]
@liuzicheng1987 
I just added some test.
Best regards

**Comment by liuzicheng1987** [comment]
Hi @ttamttam 

thanks for adding the tests. Sorry it took me four days to respond, I must habe somehow missed it. The tests look great. I will run them and (if everything goes well) then merge.

**Comment by liuzicheng1987** [comment]
Hi @ttamttam, 

compilation has failed. 

I think you need to just rearrange the code a bit: Just put the struct declaration before the declaration of the operator()== and you should be fine.

I promise next time I will be faster to review the changes.

**Comment by liuzicheng1987** [comment]
@ttamttam , looks great! Thank you for your contribution!

**Pull request merged**
