### PR TITLE
added a new method of implementing a custom parser using a Reflector …

### PR DESCRIPTION
**Pull request by BjornSAIM**
see: https://github.com/getml/reflect-cpp/issues/141

### CODE REVIEW

**Comment by liuzicheng1987** [comment]
A couple of quick comments:

1. I don't see any implementation of the reflector itself, only a concept...if people are going to use this, wouldn't you have to provide an implementation as well?
2. Could you add a test (only for JSON, there is no need to copy + paste it into all the formats)?
3. Could you also add some documentation on how to use your class? (If it's too much of a hassle, I can do it as well, no problem).
4. Very minor thing: In this library, we generally use CamelCase for types and classes...so could you rename "refl_type" into something like "ReflType"?

**Comment by liuzicheng1987** [comment]
But it is such a great idea, thank you so much!

**Comment by BjornSAIM** [comment]
> A couple of quick comments:
> 
> 1. Could you add a test (only for JSON, there is no need to copy + paste it into all the formats)?
> 2. Could you also add some documentation on how to use your class? (If it's too much of a hassle, I can do it as well, no problem).
> 3. Very minor thing: In this library, we generally use CamelCase for types and classes...so could you rename "refl_type" into something like "ReflType"?

check, check and check

**Comment by liuzicheng1987** [comment]
@BjornSAIM , this looks great. 

If the tests run through fine, I will merge it. I'm actually currently on a train and have almost reached my location, so I won't be able to merge it right now. But it will find some time some time today.

Thank you so much for your contribution!

**Comment by liuzicheng1987** [comment]
@BjornSAIM and @DaedieCool , sorry, I had a very busy weekend so I didn't get to merging this until now. But, again, thank you so much for this great addition to the library.

**Pull request merged**
