### PR TITLE
Using current CTRE (6cd1fdc) https://github.com/hanickadot/compile-ti…

### PR DESCRIPTION
**Pull request by Urfoex**
…me-regular-expressions/blob/main/single-header/ctre.hpp which should fix clang 19 usage https://github.com/getml/reflect-cpp/issues/221

### CODE REVIEW

**Comment by liuzicheng1987** [comment]
Thanks!

**Comment by liuzicheng1987** [comment]
Could you also update the vcpkg.json?

https://github.com/getml/reflect-cpp/blob/main/vcpkg.json

**Review by liuzicheng1987 — COMMENTED** [review]
Could you also update the vcpkg.json?

https://github.com/getml/reflect-cpp/blob/main/vcpkg.json

Other than that, LGTM. Thanks for the initiative.

**Comment by Urfoex** [comment]
> Could you also update the vcpkg.json?
> 
> https://github.com/getml/reflect-cpp/blob/main/vcpkg.json
> 
> Other than that, LGTM. Thanks for the initiative.

@liuzicheng1987 
Latest released version is 3.9.0 
https://vcpkg.link/ports/ctre
https://github.com/hanickadot/compile-time-regular-expressions/releases

But fix is from later, from June
https://github.com/hanickadot/compile-time-regular-expressions/commit/acb2f4de2e24a06280088377e47534137c0bc759

So, it would still miss the fix

**Comment by liuzicheng1987** [comment]
Ok

**Pull request merged**
